### PR TITLE
Week1

### PR DESCRIPTION
**Pull request by stephskas**
Lesson 1 setup

### CODE REVIEW

**Comment by stephskas** [comment]
Lesson 01-intro
Lesson 02-globals
Lesson 03-modules
Lesson 04-names
Lesson 05-utils
Lesson 06-alternative-flavor
Lesson 07-mind-grenade
Lesson 08-os-module
Lesson 09-path-module
Lesson 10-fs-sync
Lesson 11-fs-async
Lesson 12-http

**Review by akosasante — COMMENTED** [review]
Great job with the work in `answers` directory for modules 01 to 12. 

I noticed that there are some changes in this PR in the `1-event-loop-examples` folder and for the following files, that I wouldn't expect for week 1:

*   `12-http.js`
*   `14-request-event.js`
*   `15-create-big-file.js`

Just wanted to check if you intended to make those changes or were testing things out in this branch or something?

As well, I notice that the `content` directory also includes all the modules 01-17 again. Did you intend to copy or move those js files into that directory? Those copies should not be needed, you can just delete them. As well your `subfolder` directory seems to have been moved out of where it was originally inside the `content` directory.

Lastly, I notice you have some text files like `first.txt` or `result-async.txt` that have ended up outside of your `content` directory. When you run your scripts for `10-fs-sync.js` and `11-fs-async.js` , if they work correctly, they should be expecting to read files inside of the `content` directory, and writing the resulting file into the `content` directory as well.

Please let me know if you have any questions or if there's anything I can clarify by replying to this Github comment

**Comment by stephskas** [comment]
Thanks Akosasante! I had completed week1 and then had some problems with nested git repos and so I rebuilt the directories and my answers. I've made the corrections removing the extra files and correcting the file directories. Please let me know if I need to make any other modifications to my file structure or files. Thanks again for your time and review!

**Review by akosasante — APPROVED** [review]
Great @stephskas  it's looking a lot cleaner now! 

I think the only thing left is you can probably delete the JS files inside the `content/` directory. That directory should just be the `txt` files that are generated by scripts.

Your answers are in `answers/` directory :white\_check\_mark: 

And the original scripts are in the `01-node-tutorial/` top directory :white\_check\_mark:

**Pull request merged**
